config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :cars do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, except: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auto.rb
class Auto < ApplicationRecord
  belongs_to :booking
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :car
  belongs_to :user
end

app/models/car.rb
class Car < ApplicationRecord
  has_many :bookings, dependent: :destroy
  belongs_to :user
  has_one_attached :photo

end

app/models/user.rb
class User < ApplicationRecord
  has_many :cars
  has_many :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.where(user: current_user)
  end

  def new
    @booking = Booking.new
    @car = Car.find(params[:car_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @car = Car.find(params[:car_id])
    @booking.car = @car
    @booking.user = current_user

    if @booking.save
      @car.disponible = false
      @car.save
      redirect_to car_path(@car)
    else
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @car = @booking.car
    @car.disponible = true
    @car.save
    @booking.destroy
    redirect_to cars_path
  end

  private

  def booking_params
    params.require(:booking).permit(:fecha_inicio, :fecha_fin)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  def index
    @cars = Car.where(user: current_user)
  end

  #show, edit, destroy, update, new, create
  def show
    @car = Car.find(params[:id])
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.user = current_user
    if @car.save
      redirect_to car_path(@car)
    else
      render :new
    end
  end

  def edit
    @car = Car.find(params[:id])
  end

  def update
    @car = Car.find(params[:id])
    @car.update(car_params)
    redirect_to car_path(@car) #debería redirigir al show/id
  end

  def destroy
    @car = Car.find(params[:id])
    @car.destroy
    redirect_to cars_path
  end

  private
  def car_params
    params.require(:car).permit(:modelo, :anio, :precio, :ubicacion, :detalles, :capacidad, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @cars = Car.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container" id="containerbookings">
<div class="row">
  
  <div class="col-6">
      <br>
      <h1> Mis reservas</h1>
      <p> Usted tiene reservas en las siguientes fechas:</p>
  </div>
  <div class="col-6 ">
      <div class="right text-end">
          <br>
          <%= link_to "Ver mis autos" , cars_path, class: 'btn btn-outline-secondary' %>
      </div>
  </div>
</div>
</div>
</div>
<div class="container" id="containerbookings">
  
  <% @bookings.each do |booking| %>
    <div class="card-product mt-4">
      <% if booking.car.photo.key %>
        <%= cl_image_tag booking.car.photo.key%>
      <% end %>
      <div class="card-product-infos">
        <h5><strong>Modelo:</strong> <%= booking.car.modelo %></h5>
        <h5><strong> Capacidad:</strong> <%= booking.car.capacidad %> personas</h5>
        <h5><strong> Fecha: </strong><%=booking.fecha_inicio%> al <%=booking.fecha_fin%>.</h5>
        <h5> <strong>Total de días: </strong><%= booking.fecha_fin-booking.fecha_inicio %></h5>
        <br>
        <%= link_to "Anular reserva" , booking_path(booking), class:"btn btn-outline-primary", method: :delete %></p>
      </div>
    </div>
  <% end %>

  
</div>

app/views/bookings/new.html.erb
<%= simple_form_for [@car, @booking] do |f| %>

  <%= f.input :fecha_inicio, as: :date %>
  <%= f.input :fecha_fin, as: :date %>
  <%# <%= f.hidden_field :car_id, :value => params[:car_id] %>


  <%= f.submit "Agendar en las fechas indicadas", class: "btn btn-primary" %>
<% end %>

app/views/cars/edit.html.erb
<%# Formulario edit y new %>
<div class="container">
  <h2>Editar</h2>
  <br>
  <%= simple_form_for(@car) do |f| %>
    <%= f.input :modelo %>
    <%= f.input :anio, label: :Año %>
    <%= f.input :precio %>
    <%= f.input :ubicacion, label: :Ubicación%>
    <%= f.input :detalles %>
    <%= f.input :capacidad %>
    <%= f.input :photo, as: :file %>
    <%= f.submit %>
  <% end %>
  <br>
  <br>
</div>

app/views/cars/index.html.erb
<h1 class="p-3"> Mis Autos </h1>
<div class="p-3">
  <%= link_to "Agregar auto" , new_car_path, class: 'btn btn-outline-secondary' %>
</div>

<div class="container" id="containerindex">

  <% @cars.each do |car| %>
    <div class="card" style="width: 18rem;">
       <% if car.photo.key %>
        <%= cl_image_tag car.photo.key, style: "height: 150px; width: 100%;"%>
      <% end %>
      <h5>
      <%=car.modelo.capitalize %>
      </h5>
      <div class="list-group list-group-flush">
        <li class="list-group-item"><strong><%= link_to "Ver detalle", car_path(car), class: 'btn btn-outline-secondary' %></strong></li>
        <li class="list-group-item"><%= link_to "Modificar", edit_car_path(car), class: 'btn btn-outline-secondary' %></li>
        <li class="list-group-item"><%= link_to "Eliminar", car_path(car), method: :delete, data: { confirm: "Are you sure you want to delete this car?" }, class: 'btn btn-outline-secondary'%></li>
      </div>

    </div>
    <% end %>
</div>

app/views/cars/new.html.erb
<div class="container py-5">
<div class="bg-white rounded p-3 shadow">
  <h3>Agregar un auto</h3>
  <%= simple_form_for @car do |f| %>
    <%= f.input :modelo %>
    <%= f.input :anio, label: :Año %>
    <%= f.input :precio %>
    <%= f.input :ubicacion, label: :Ubicación %>
    <%= f.input :detalles %>
    <%= f.input :capacidad %>
    <%= f.input :photo, as: :file %>
    <%= f.submit class: 'btn btn-outline-secondary' %> <%= link_to "Volver", cars_path, class: 'btn btn-outline-secondary'%>
  <% end %>
</div>
</div>

app/views/cars/show.html.erb
  <div class="card-product">
    <%= cl_image_tag @car.photo.key%>
    <div class="card-product-infos">
      <h3><%= @car.modelo.capitalize %></h3>
      <p><%= @car.anio %></p>
      <p><%= @car.precio %></p>
      <p><%= @car.ubicacion %></p>
      <p><%= @car.detalles %></p>
      <p><%= @car.capacidad %></p>
    </div>
  </div>
<div class="container">
  <table class="table">
  <thead>
    <tr>
      <th scope="col">Código de reserva</th>
      <th scope="col">Fecha de inicio</th>
      <th scope="col">Fecha de término</th>
      <th scope="col">Acciones</th>
    </tr>
  </thead>
  <tbody>
      <% @car.bookings.each do |booking| %>
    <tr>
      <th scope="row"><%=  booking.id %></th>
      <td><%= booking.fecha_inicio %></td>
      <td><%= booking.fecha_fin %></td>
      <td><%= link_to "Anular reserva" , booking_path(booking), class:"btn btn-outline-primary", method: :delete %></p></td>
    </tr>
       <% end %>
  </tbody>
  </table>


  <br>
</div>
<%= link_to 'Volver', cars_path, class: "btn btn-primary"%>
<%= link_to 'Alquilar este auto', new_car_booking_path(@car), class: "btn btn-primary"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeyondSchool</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "pages/navbar" %>
    <%= yield %>

  </body>
</html>

app/views/pages/_card.html.erb
<div class="d-flex">
  <div class="card" style="width: 18rem;">
    <%# <% @cars.each do |car| %> %>
    <img src="https://images.unsplash.com/photo-1646161535915-4b9701625ba5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2071&q=80" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">modelo</h5>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item"><i class="fa-solid fa-location-dot"></i> Valdivia, Chile</li>
      <li class="list-group-item">
      <i class="fa-solid fa-users"></i>
      4 passengers</li>
      <li class="list-group-item price"><strong>$400</strong></li>
    </ul>
    <%# <% end %>
    <div class="card-body">
      <a href="#" class="card-link btn btn-success">Book this car</a>
      <a href="#" class="card- btn btn-outline-success btn-sm">View details</a>
    </div>
  </div>
</div>

app/views/pages/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    © 2022 Hecho con <i class="fas fa-heart"></i> por Lewagon's Students.
  </div>
</div>

app/views/pages/_form.html.erb
<%# Formulario edit y new %>
<br><br><br><br><br>

<%= simple_form_for(@cars) do |f| %>
  <%= f.input :modelo %>
  <%= f.input :anio %>
  <%= f.input :precio %>
  <%= f.input :ubicacion %>
  <%= f.input :detalles %>
  <%= f.input :capacidad %>
  <%= f.submit %>
<% end %>

app/views/pages/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to cars_path, class: "navbar-brand" do %>
      <%= image_tag "https://www.welovesolo.com/wp-content/uploads/2014/08/p16fepdsn31csuana114r1qr217ra9-details.jpg" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <% if current_user %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%= link_to "Ir a Home", root_path, class: "nav-link"%>
        <%# if user_signed_in? %>
          <li class="nav-item active">
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://cdn2.iconfinder.com/data/icons/audio-16/96/user_avatar_profile_login_button_account_member-512.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Mis Reservas", bookings_path, class: "dropdown-item" %>
              <%= link_to "Mis Autos", cars_path, class: "dropdown-item" %>
              <%= link_to "Agregar un auto", new_car_path, class: "dropdown-item" %>
              <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete, class: "dropdown-item" %>

            </div>
          </li>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
    <% else  %>
    <%= link_to "Iniciar sesión", new_user_session_path, class:'btn btn-outline-primary' %>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: url('https://res.cloudinary.com/dydeg1evr/image/upload/v1652469043/development/fondo_wtl4tk.jpg')">
  <div class="container_uno">
    <h1>La comodidad de viajar en auto va contigo</h1>
    <p>Reserva tu auto y ten una experiencia increíble</p>
    <a href="#" class="btn-banner"> <%= link_to "Ver Autos disponibles" , new_user_session_path,class: 'btn btn-secondary' %></a>
  </div>
</div>

<div class="container" id="containerhome">
  <% @cars.each do |car| %>
    <% if car.disponible  %>
      <div class="card" style="width: 18rem;">
        <%= cl_image_tag car.photo.key, class: "card-img-top", style: "height: 150px; width: 100%;"%>

        <div class="card-body">
          <h5 class= "card-title"><%= car.modelo %></h5>
          <p class="card-text"><i class="fa-solid fa-location-dot"></i>  <%= car.ubicacion %></p>
          <p class="card-text"><i class="fa-solid fa-users"></i>  <%= car.capacidad %></p>
          <p class="card-text"><strong>$  <%= car.precio %></strong></p>
            <div class="buttons d-flex">
            <% if user_signed_in? %>
              <%= link_to "Alquilar", new_car_booking_path(car), class: "btn btn-outline-primary"  %>
              <%= link_to "Ver detalles", car_path(car), class: "btn btn-outline-primary"  %>
            <% else %>
              <%= link_to "Alquilar", new_user_session_path, class:"btn btn-outline-primary" %>
              <%= link_to "Ver detalles", new_user_session_path, class:"btn btn-outline-primary" %>
            <% end %>
            </div>
        </div>

      </div>
    <% end %>
  <% end %>
</div>